### PR TITLE
label cephfs pvc for cg

### PR DESCRIPTION
**Pull request by youhangwang**

### CODE REVIEW

**Review by ELENAGER — APPROVED** [review]
LGTM

**Review by BenamarMk — APPROVED** [review]

**Comment by ShyamsundarR** [comment]
@youhangwang is the e2e test failure related?

**Comment by youhangwang** [comment]
> @youhangwang is the e2e test failure related?

No, it's passed local run. 
```
2024-08-08T11:58:35.982+0800    INFO    util/crud.go:96 channel ramen-gitops is deleted
--- PASS: TestSuites (0.37s)
    --- PASS: TestSuites/Validate (0.10s)
        --- PASS: TestSuites/Validate/CheckRamenHubOperatorStatus (0.04s)
        --- PASS: TestSuites/Validate/CheckRamenSpokeOperatorStatus (0.06s)
    --- PASS: TestSuites/Exhaustive (0.00s)
        --- PASS: TestSuites/Exhaustive/Deployment-0 (0.00s)
            --- PASS: TestSuites/Exhaustive/Deployment-0/Subscription (436.63s)
                --- PASS: TestSuites/Exhaustive/Deployment-0/Subscription/Deploy (5.45s)
                --- PASS: TestSuites/Exhaustive/Deployment-0/Subscription/Enable (120.38s)
                --- PASS: TestSuites/Exhaustive/Deployment-0/Subscription/Failover (125.44s)
                --- PASS: TestSuites/Exhaustive/Deployment-0/Subscription/Relocate (155.19s)
                --- PASS: TestSuites/Exhaustive/Deployment-0/Subscription/Disable (30.07s)
                --- PASS: TestSuites/Exhaustive/Deployment-0/Subscription/Undeploy (0.11s)
        --- PASS: TestSuites/Exhaustive/Deployment-1 (0.00s)
            --- PASS: TestSuites/Exhaustive/Deployment-1/Subscription (558.81s)
                --- PASS: TestSuites/Exhaustive/Deployment-1/Subscription/Deploy (35.46s)
                --- PASS: TestSuites/Exhaustive/Deployment-1/Subscription/Enable (120.40s)
                --- PASS: TestSuites/Exhaustive/Deployment-1/Subscription/Failover (217.54s)
                --- PASS: TestSuites/Exhaustive/Deployment-1/Subscription/Relocate (155.19s)
                --- PASS: TestSuites/Exhaustive/Deployment-1/Subscription/Disable (30.07s)
                --- PASS: TestSuites/Exhaustive/Deployment-1/Subscription/Undeploy (0.14s)
PASS
ok      github.com/ramendr/ramen/e2e    559.224s
```

**Comment by youhangwang** [comment]
https://github.com/RamenDR/ramen/issues/1501

**Pull request merged**
