### PR TITLE
Delay UserPl finalizer removal till DRPC is finalized

### PR DESCRIPTION
**Pull request by ShyamsundarR**
Current order of finalizer addition is DRPC resource first,
followed by UserPl. The order of removal is the reverse.

During removal though, the finalizer on the UserPl is removed
earlier than completion of finalizing DRPC.

In case of any reconciles post initial start of deletion, the
userPl would be garbage collected, and if DRPC is not deleted
but the user placement is, then future reconciles will not
continue the deletion process as isBeingDeleted will find neither
the DRPC as being deleted, or the UserPl to continue processing
deletion.

This commit delays the removal of UserPl finalizer to after
processing of DRPC for deletion, such that if the deletion was
processed based on the UserPl deletion, it will complete the
process and ensures the PlRule is not deleted till then.

There is still a race, where post removal of the UserPl finalizer
the update for DRPC finalizer removal fails, at which point a
future reconcile will not pick up the fact that it is a delete
operation, and would keep reporting UserPl missing. But, this
does not leak any resource as such.

Signed-off-by: Shyamsundar Ranganathan <srangana@redhat.com>

### CODE REVIEW

**Review by BenamarMk — COMMENTED** [review]
I think this change is unnecessary but I may not fully understand the exact issue.  So from the description, the issue is the UserPl is garbage collected before DRPC deletion is fully processed.  The next reconciliation will not run `processDeletion` because `isBeingDeleted` returns false.  But the`isBeingDeleted` will return true in this case:
`!drpc.GetDeletionTimestamp().IsZero()` OR
`(usrPlRule != nil && !usrPlRule.GetDeletionTimestamp().IsZero())`
Hmmmm, so we should `processDeletion` because the first part is true. Am I missing something?

Nevertheless, this patch is still good. but it is not fixing the issue the way I understand it.

**Comment by ShyamsundarR** [comment]
> I think this change is unnecessary but I may not fully understand the exact issue. So from the description, the issue is the UserPl is garbage collected before DRPC deletion is fully processed. The next reconciliation will not run `processDeletion` because `isBeingDeleted` returns false. But`isBeingDeleted` will return true in this case: `!drpc.GetDeletionTimestamp().IsZero()` OR `(usrPlRule != nil && !usrPlRule.GetDeletionTimestamp().IsZero())` Hmmmm, so we should `processDeletion` because the first part is true. Am I missing something?

The case is UserPl deletion and DRPC is not deleted, which results in UserPl getting garbage collected earlier, and in a subsequent reconcile,
- `!drpc.GetDeletionTimestamp().IsZero()` is false (DRPC not deleted)
- `(usrPlRule != nil && !usrPlRule.GetDeletionTimestamp().IsZero())` is also false as userPl is nil

I guess the comment is not clear enough (or does not call this out explicitly)

> 
> Nevertheless, we may still want this change in order to make things robust, but it may not be fixing the issue the way I understand it.

One further improvement, not made as part of this PR, is to add UserPl as an owner for the DRPC. This would then result in DRPC getting deleted if the UserPl is deleted, and we can do away with the UserPl finalizer and ensure we delete as required (without the last potential DRPC finalizer removal race). I will add an issue for the same.

**Review by BenamarMk — COMMENTED** [review]
Got it. DRPC wasn't deleted.

**Review by BenamarMk — APPROVED** [review]

**Comment by ShyamsundarR** [comment]
Test [failure](https://github.com/RamenDR/ramen/runs/7488256713?check_suite_focus=true#step:5:212) is due to DRPC status updated when it was not expected to. Rerunning the tests as this is not related, but may have a fix subsequently for the flake.

**Pull request merged**
