### PR TITLE
ramen: disable stacktrace by default

### PR DESCRIPTION
**Pull request by Madhu-1**
skipping the stack trace while logging by default and add configuration to print the timestamp in logging.

reference: https://github.com/csi-addons/volume-replication-operator/pull/105

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

### CODE REVIEW

**Comment by ShyamsundarR** [comment]
@Madhu-1 We want to retain stack traces for now... Not sure we want this disabled as yet.

**Comment by Madhu-1** [comment]
@ShyamsundarR even running in production also?

**Comment by ShyamsundarR** [comment]
> @ShyamsundarR even running in production also?

yes, we may shift to the JSON based logging, but otherwise for now we retain the stack trace, as that helps debugging and the project is still too fresh to disable the same.

**Comment by Madhu-1** [comment]
> we may shift to the JSON based logging, but otherwise for now we retain the stack trace, a

Sounds good. Closing

**Comment by ShyamsundarR** [comment]
jFYI, initially we were also bugged that there are stack traces on error logs, so the change is useful, but just not now. Thanks though.

**Pull request closed without merging**
