### PR TITLE
WIP: Integrate VolumeReplicationGroup with VolumeReplication CR

### PR DESCRIPTION
**Pull request by raghavendrabhat**
* Until now, a shim VolumeReplication resource was being used
  instead of an actual VolumeReplication resource with proper
  controller and reconciler. This makes the change to use the
  actual resource from csi-addons and make necessary changes
  in VRG reconciler for the integration to work.

Signed-off-by: Raghavendra M <raghavendra@redhat.com>

### CODE REVIEW

**Comment by raghavendrabhat** [comment]
NOTE: Though WIP has been put, the changes are ready to be reviewed. Since for the last few days, the main focus has been to verify that integration works at the storage level (by doing failover of stateful app), WIP has been put.

**Review by BenamarMk — COMMENTED** [review]
I am not sure if this is ready for code review.  I stopped because there are comments clearly stating that the code is not complete.

**Review by ShyamsundarR — COMMENTED** [review]
I agree with the changes broadly, but,
1. Can you take a look at #43 and reconcile with the same
2. an you split moving to csi-addon VolRep and the required status checking as 2 commits

I am asking for the latter, as we need status checks more in the VRG code, as of now it is blind to actions taken. Hence would like to separate that out into its own commit/PR for more handling.

**Comment by raghavendrabhat** [comment]
https://github.com/RamenDR/ramen/pull/48 has been sent for review.

**Pull request closed without merging**
