### PR TITLE
util: fix extra linter errors

### PR DESCRIPTION
**Pull request by raghavendra-talur**
These errors were discovered when running some extra linters which are not part of the default suite. I will enable the extra linters in a different PR.

### CODE REVIEW

**Review by asn1809 — APPROVED** [review]
Lgtm

**Comment by ShyamsundarR** [comment]
@raghavendra-talur with this [golang](https://go.dev/blog/loopvar-preview) change in play, how does it impact some of the changes in this PR?

**Comment by ShyamsundarR** [comment]
> @raghavendra-talur with this [golang](https://go.dev/blog/loopvar-preview) change in play, how does it impact some of the changes in this PR?

Looks like the fix attempts to address [this](https://github.com/red-hat-storage/ramen/actions/runs/12431890055/job/34710182149?pr=429) failure. It is possible that the linters downstream are older, and hence "complaining" about the same. One option is to address this downstream only?

**Comment by raghavendra-talur** [comment]
@ShyamsundarR you are right. Closed this PR as you have already handled the backport.

**Pull request closed without merging**
