### PR TITLE
ocm-minikube-ramen.sh: rook mirroring, app namespace, s3secrets apply to spokes not all clusters

### PR DESCRIPTION
**Pull request by hatfieldbrian**
This addresses the case where there are two spokes and the hub is not one of them.

### CODE REVIEW

**Comment by ShyamsundarR** [comment]
As the e2e stands, the s3 store uses PVCs from rook-ceph to store its data on the hub. So we need a rook instance on the hub.

Also DRPC reconciler (at present) uses the S3 secret on the hub to read the s3 objects to restore, and hence the secret is required at the hub as well.

This can possibly be better addressed once #117 is merged?

**Comment by ShyamsundarR** [comment]
I did something like [thi](https://hackmd.io/RqxJgKIfTo-nFY3XgTwX4w) instead to retain a rook instance on the hub, are we still doing this @hatfieldbrian ?

**Review by vdeenadh — APPROVED** [review]
LGTM.

Note: in future, minio_deploy may be needed on spoke clusters only.

**Review by ShyamsundarR — APPROVED** [review]

**Comment by hatfieldbrian** [comment]
> As the e2e stands, the s3 store uses PVCs from rook-ceph to store its data on the hub. So we need a rook instance on the hub.

rook-ceph is still deployed to all clusters and a comment has been added indicating that it is the mirror sources, mirror targets and minio backend that require volumes.

> Also DRPC reconciler (at present) uses the S3 secret on the hub to read the s3 objects to restore, and hence the secret is required at the hub as well.
> 
> This can possibly be better addressed once #117 is merged?

I understand that s3secrets are now only needed by VRG on managed clusters, not the hub.

> I did something like [thi](https://hackmd.io/RqxJgKIfTo-nFY3XgTwX4w) instead to retain a rook instance on the hub, are we still doing this @hatfieldbrian ?

I applied these changes to this pull request.  I'm sorry I failed to mention in today's standup meeting that this pull request was not yet ready for re-review.

> Note: in future, minio_deploy may be needed on spoke clusters only.

When that happens the rook-ceph deploy loop should be modified to include spoke clusters only and the `cluster_names` variable removed.

**Pull request merged**
