### PR TITLE
Use new clusteradm json output

### PR DESCRIPTION
**Pull request by nirs**
Use new json output[1] in `clusteradm get token` to get hub info.

clusteradm 0.5.0 was released, but it tries to install version 0.10.0 of the policy
framework which was not tagged yet. We install the latest version to work around this.

With this, we can required clusteradm 0.5.0 and use the new json output to simplify
the code.

### CODE REVIEW

**Comment by nirs** [comment]
- Need rebase
- Apply changes in drenv/clusteradm.py
- Requires new clusteradm version, should be availabe on Feb 20

**Comment by nirs** [comment]
Does not work yet, ocm seems to be broken now. It tries to pull non existing image:

```
$ kubectl get deploy -n open-cluster-management --context hub
NAME                                    READY   UP-TO-DATE   AVAILABLE   AGE
cluster-manager                         1/1     1            1           24m
governance-policy-addon-controller      0/1     1            0           23m
governance-policy-propagator            0/1     1            0           23m
multicluster-operators-appsub-summary   1/1     1            1           23m
multicluster-operators-channel          1/1     1            1           23m
multicluster-operators-placementrule    1/1     1            1           23m
multicluster-operators-subscription     1/1     1            1           23m

$ kubectl logs deploy/governance-policy-addon-controller -n open-cluster-management --context hub
Error from server (BadRequest): container "manager" in pod "governance-policy-addon-controller-7b786554f5-xfqfc" is waiting to start: trying and failing to pull image

$ kubectl describe deploy/governance-policy-addon-controller -n open-cluster-management --context hub  | grep Image:
    Image:      quay.io/open-cluster-management/governance-policy-addon-controller:v0.10.0

$ podman pull quay.io/open-cluster-management/governance-policy-addon-controller:v0.10.0
Trying to pull quay.io/open-cluster-management/governance-policy-addon-controller:v0.10.0...
Error: initializing source docker://quay.io/open-cluster-management/governance-policy-addon-controller:v0.10.0: reading manifest v0.10.0 in quay.io/open-cluster-management/governance-policy-addon-controller: manifest unknown: manifest unknown
```

**Comment by nirs** [comment]
The OCM issue is not related to clusteradm 0.5.0, it breaks also with main.

The change works - getting token using json output and joining using the parsed json:

```
2023-02-13 12:48:22,020 DEBUG   [dr1/0] Joining to cluster hub
2023-02-13 12:48:22,025 DEBUG   [dr2/0] deployment "cluster-manager-work-webhook" successfully rolled out
2023-02-13 12:48:22,030 DEBUG   [dr2/0] Joining to cluster hub
2023-02-13 12:48:22,245 DEBUG   [dr2/0] Wait for klusterlets.operator.open-cluster-management.io crd to be established
2023-02-13 12:48:22,245 DEBUG   [dr2/0] Wait  for klusterlets.operator.open-cluster-management.io crd to be ready
2023-02-13 12:48:45,190 DEBUG   [dr2/0] Please log onto the hub cluster and run the following command:
2023-02-13 12:48:45,190 DEBUG   [dr2/0] 
2023-02-13 12:48:45,190 DEBUG   [dr2/0]     clusteradm accept --clusters dr2
2023-02-13 12:48:45,190 DEBUG   [dr2/0] 
2023-02-13 12:48:45,192 DEBUG   [dr2/0] Accepting cluster
2023-02-13 12:48:45,233 DEBUG   [dr2/0] Starting approve csrs for the cluster dr2
2023-02-13 12:48:45,239 DEBUG   [dr2/0] CSR dr2-pxg5q approved
2023-02-13 12:48:45,270 DEBUG   [dr2/0] set hubAcceptsClient to true for managed cluster dr2
2023-02-13 12:48:45,270 DEBUG   [dr2/0] 
2023-02-13 12:48:45,270 DEBUG   [dr2/0]  Your managed cluster dr2 has joined the Hub successfully. Visit https://open-cluster-management.io/scenarios or https://github.com/open-cluster-management-io/OCM/tree/main/solutions for next steps.
2023-02-13 12:48:45,272 DEBUG   [dr2/0] Enabling addons
2023-02-13 12:48:45,336 DEBUG   [dr2/0] Deploying application-manager add-on to namespaces open-cluster-management-agent-addon of managed cluster: dr2.
2023-02-13 12:48:45,361 DEBUG   [dr2/0] Deploying config-policy-controller add-on to namespaces open-cluster-management-agent-addon of managed cluster: dr2.
2023-02-13 12:48:46,833 DEBUG   [dr1/0] Please log onto the hub cluster and run the following command:
2023-02-13 12:48:46,833 DEBUG   [dr1/0] 
2023-02-13 12:48:46,833 DEBUG   [dr1/0]     clusteradm accept --clusters dr1
2023-02-13 12:48:46,833 DEBUG   [dr1/0] 
2023-02-13 12:48:46,836 DEBUG   [dr1/0] Accepting cluster
2023-02-13 12:48:46,880 DEBUG   [dr1/0] Starting approve csrs for the cluster dr1
2023-02-13 12:48:46,892 DEBUG   [dr1/0] CSR dr1-mzqh4 approved
2023-02-13 12:48:46,911 DEBUG   [dr1/0] set hubAcceptsClient to true for managed cluster dr1
2023-02-13 12:48:46,911 DEBUG   [dr1/0] 
2023-02-13 12:48:46,911 DEBUG   [dr1/0]  Your managed cluster dr1 has joined the Hub successfully. Visit https://open-cluster-management.io/scenarios or https://github.com/open-cluster-management-io/OCM/tree/main/solutions for next steps.
```

**Comment by rakeshgm** [comment]
well, the missing addon `governance-policy-addon-controller` should have been installed from OCM as the default unless it's changed in the latest release.

**Comment by nirs** [comment]
@rakeshgm according to the docs the policy framework is install via the hub-addon commmand:
https://open-cluster-management.io/getting-started/integration/policy-framework/

This PR does not change anything related to this, just using the json output available
in clusteradm 0.5.0.

The PR works, but OCM is currently broken, trying to pull non existing tag from quay for
the policy framework deployments.

**Review by rakeshgm — APPROVED** [review]

**Review by ycyaoxdu — COMMENTED** [review]
/lgtm @nirs

**Review by ShyamsundarR — APPROVED** [review]

**Pull request merged**
