### PR TITLE
e2e: move channel operations into exhaustive tests

### PR DESCRIPTION
**Pull request by raghavendra-talur**

### CODE REVIEW

**Comment by raghavendra-talur** [comment]
> this change looks fine if we only have exhaustive test. But if later we have other test suites also need use channel, then we need create channel in other test suites as well. And it seems to me that the channel will not change for different test suites.
> 
> So could you please comment your reason to move channel operations into exhaustive tests? thanks @raghavendra-talur

I would like to keep the validate test suite to be read only. Without moving the channel operations inside the other specific tests it is not possible.

**Comment by ShyamsundarR** [comment]
> this change looks fine if we only have exhaustive test. But if later we have other test suites also need use channel, then we need create channel in other test suites as well. And it seems to me that the channel will not change for different test suites.
> 
> So could you please comment your reason to move channel operations into exhaustive tests? thanks @raghavendra-talur

The way I see it, the channel is needed for the test suites that are going to use it, so moving it to exhaustive is good. Also, the point that if  create another test suite that does dr actions, then it would also create a channel, but we need to handle that when/how we can when we get to it.

So I am fine with the change, but would like your ack on this @par97

**Comment by par97** [comment]
I think we could move all the test suites into a func that is the same level of validate func. So we could keep validate test read only and also avoid to create/delete channel for each test suite and manage delete conflicts. Like this:

```
func TestSuites(t *testing.T) {
         if !t.Run("Validate", Validate) {
		t.Fatal("failed to validate the test suite")
	}

	t.Run("RunSuites", RunSuites)
}

func RunSuites(t *testing.T) {
	if err := util.EnsureChannel(); err != nil {
		t.Fatalf("failed to ensure channel: %v", err)
	}

	t.Cleanup(func() {
		if err := util.EnsureChannelDeleted(); err != nil {
			t.Fatalf("failed to ensure channel deleted: %v", err)
		}
	})

	for _, suite := range Suites {
		t.Run(suite.name, suite.test)
	}
}
```

what do you think?

**Comment by raghavendra-talur** [comment]
> And it seems to me that the channel will not change for different test suites.

> So we could keep validate test read only and also avoid to create/delete channel for each test suite and manage delete conflicts.

Actually, IMO different suites might require different channel. Also, every suite should be self sufficient. Isn't channel creation an operation similar to Deploy or Enable? It should be at the same level as Deploy and Enable.

**Comment by par97** [comment]
> > And it seems to me that the channel will not change for different test suites.
> 
> > So we could keep validate test read only and also avoid to create/delete channel for each test suite and manage delete conflicts.
> 
> Actually, IMO different suites might require different channel. Also, every suite should be self sufficient. Isn't channel creation an operation similar to Deploy or Enable? It should be at the same level as Deploy and Enable.

Current implementation is all based on we will only use one channel (with info of giturl) for all the tests. That is why we define following in the util/const.go, not in each test suite.

```
	defaultChannelName      = "ramen-gitops"
	defaultChannelNamespace = "ramen-samples"
	defaultGitURL           = "https://github.com/RamenDR/ocm-ramen-samples.git"
```

so the question is, shall we keep only one channel, or shall we allow multiple channels for different workload?

**Comment by ShyamsundarR** [comment]
> > And it seems to me that the channel will not change for different test suites.
> 
> > So we could keep validate test read only and also avoid to create/delete channel for each test suite and manage delete conflicts.
> 
> Actually, IMO different suites might require different channel. Also, every suite should be self sufficient. Isn't channel creation an operation similar to Deploy or Enable? It should be at the same level as Deploy and Enable.

Test suites, unless hard coded with a channel, would use the global channel IMO. Otherwise we get into options per test suite (which if the need arises would be added). At this point the suite knows that it should use a specific channel if not the global and so the suite would create the channel.

**Comment by ShyamsundarR** [comment]
> I think we could move all the test suites into a func that is the same level of validate func. So we could keep validate test read only and also avoid to create/delete channel for each test suite and manage delete conflicts. Like this:
> 
> ```
> func TestSuites(t *testing.T) {
>          if !t.Run("Validate", Validate) {
> 		t.Fatal("failed to validate the test suite")
> 	}
> 
> 	t.Run("RunSuites", RunSuites)
> }
> 
> func RunSuites(t *testing.T) {
> 	if err := util.EnsureChannel(); err != nil {
> 		t.Fatalf("failed to ensure channel: %v", err)
> 	}
> 
> 	t.Cleanup(func() {
> 		if err := util.EnsureChannelDeleted(); err != nil {
> 			t.Fatalf("failed to ensure channel deleted: %v", err)
> 		}
> 	})
> 
> 	for _, suite := range Suites {
> 		t.Run(suite.name, suite.test)
> 	}
> }
> ```
> 
> what do you think?

There could/would be other test suites that do not require the channel to be present.

I do understand the create/delete by different suites can cause confusion. This is where we possibly need something common for test suites that need the channel, but I would rather solve that when we add another test suite that has such common requirements than now.

**Comment by raghavendra-talur** [comment]
@par97 Are you concerns addressed for this PR?

**Comment by ShyamsundarR** [comment]
> @par97 Are you concerns addressed for this PR?

Merging this, we should be ok going forward.

**Review by ShyamsundarR — APPROVED** [review]

**Pull request merged**
