### PR TITLE
ocm-minikube-ramen.sh: volume-rep-class remove

### PR DESCRIPTION
**Pull request by hatfieldbrian**
Signed-off-by: bhatfiel <bhatfiel@redhat.com>

### CODE REVIEW

**Comment by hatfieldbrian** [comment]
This pull request should be merged after https://github.com/RamenDR/ramen/pull/121 is.

**Comment by ShyamsundarR** [comment]
This would also need a change to the created [VolRepClass](https://github.com/RamenDR/ramen/blob/6a96d8f749d1b806fd64615140a0c033155fc5d3/hack/minikube-rook-mirror-setup.sh#L82-L92) to add a schedule as a parameter in there, that can match the DRPolicy set schedule. This enabled VRG to find the right Replication class to use.

**Comment by hatfieldbrian** [comment]
> This pull request should be merged after #121 is.

Pull request #182 replaced #121 (see https://github.com/RamenDR/ramen/pull/121#issuecomment-892080388) and has been merged.

**Comment by hatfieldbrian** [comment]
> This would also need a change to the created [VolRepClass](https://github.com/RamenDR/ramen/blob/6a96d8f749d1b806fd64615140a0c033155fc5d3/hack/minikube-rook-mirror-setup.sh#L82-L92) to add a schedule as a parameter in there, that can match the DRPolicy set schedule. This enabled VRG to find the right Replication class to use.

This has been addressed in the version of this pull request just pushed.  Please review.

**Review by ShyamsundarR — APPROVED** [review]

**Pull request merged**
