### PR TITLE
Cleanup setting of KUBEBUILDER_ASSETS

### PR DESCRIPTION
**Pull request by nirs**
Was duplicated 4 times in different files. Replace with a symlink created when setting
envtest.

### CODE REVIEW

**Review by ShyamsundarR — COMMENTED** [review]
I do not understand the need or motivation for this PR, what is it solving?

Operator-sdk defaults setup of KUBEBUILER_ASSETS in the Makefile, this can be overridden when not using the Makefile by an env variable.

With this change the makefile is not setting KUBEBUILDER_ASSETS, which is wrong and I would prefer not to do this and leave it in the default pattern.

**Comment by nirs** [comment]
> I do not understand the need or motivation for this PR, what is it solving?

Replacing duplicate code with simpler code that does not need to change when upgrading k8s version (defined in the makefile, hardcoded in the test suites) or when setup-envtest
changes its implementation details (e.g. `{k8s}/{version)-{os}-{arch}`).

> Operator-sdk defaults setup of KUBEBUILER_ASSETS in the Makefile, this can be overridden when not using the Makefile by an env variable.

This variable is pointless since it was not used in the makefile, and was *not* exported
to the `go test` child process.

> With this change the makefile is not setting KUBEBUILDER_ASSETS, which is wrong 

What is this wrong? what is the purpose of setting it in the makefile?

**Comment by nirs** [comment]
To make it more clear:

```
setup-envtest: envtest
    KUBEBUILDER_ASSETS="$(shell $(ENVTEST_ASSETS_DIR)/setup-envtest use $(ENVTEST_K8S_VERSION) --bin-dir $(ENVTEST_ASSETS_DIR) -p path)"
```

This does not set the make variable `KUBEBUILDER_ASSETS`, but a variable in the temporary
shell used to run the command. The value is dropped immediately and no other part of
the makefile can use it. Overriding the value using the command line has no effect.

**Comment by ShyamsundarR** [comment]
> > I do not understand the need or motivation for this PR, what is it solving?
> 
> Replacing duplicate code with simpler code that does not need to change when upgrading k8s version (defined in the makefile, hardcoded in the test suites) or when setup-envtest changes its implementation details (e.g. `{k8s}/{version)-{os}-{arch}`).
> 
> > Operator-sdk defaults setup of KUBEBUILER_ASSETS in the Makefile, this can be overridden when not using the Makefile by an env variable.
> 
> This variable is pointless since it was not used in the makefile, and was _not_ exported to the `go test` child process.
> 
> > With this change the makefile is not setting KUBEBUILDER_ASSETS, which is wrong
> 
> What is this wrong? what is the purpose of setting it in the makefile?

KUBEBUILDER_ASSETTS is the variable env tests uses [internally](https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/envtest/doc.go), hence we need to set the same. 

If the make file was not setting it, then fixing that is needed. I want to retain KUBEBUILDER_ASSETS explicit than hide the variable.

**Comment by nirs** [comment]
> KUBEBUILDER_ASSETTS is the variable env tests uses [internally](https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/envtest/doc.go), hence we need to set the same.

We need to set it only if we need it or pass it to the go test command.
 
> If the make file was not setting it, then fixing that is needed. I want to retain KUBEBUILDER_ASSETS explicit than hide the variable.

Do you suggest to run `go test` as:
 
   KUBEBUILDER_ASSETS=$(KUBEBUILDER_ASSETS) go test ...

Can be done by exporting the variable in the top level of the makefile:

    export KUBEBUILDER_ASSETS = ...

But it does not eliminate the need to remove the duplicate settings in the suites.

**Comment by BenamarMk** [comment]
@nirs maybe we are spending too much time on this. I aimed for simplicity and probably we should just stick to that. Nonetheless, I executed your PR, and I received the output below. I opted not to expend even a minute on troubleshooting it. I am merely posting it here for your reference.

```
make test-drpc     
bash: testbin/golangci-lint: No such file or directory
/Users/benamar/projects/github/ramen/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
/Users/benamar/projects/github/ramen/bin/controller-gen rbac:roleName=operator-role crd:generateEmbeddedObjectMeta=true webhook paths="./..." output:crd:artifacts:config=config/crd/bases
mkdir -p /Users/benamar/projects/github/ramen/testbin
test -s /Users/benamar/projects/github/ramen/testbin/setup-envtest || GOBIN=/Users/benamar/projects/github/ramen/testbin go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
current="$(/Users/benamar/projects/github/ramen/testbin/setup-envtest use 1.25.0 --bin-dir /Users/benamar/projects/github/ramen/testbin --print path)"; \
			ln --symbolic --force --no-target-directory "$current" "/Users/benamar/projects/github/ramen/testbin/current"
ln: illegal option -- -
usage: ln [-s [-F] | -L | -P] [-f | -i] [-hnv] source_file [target_file]
       ln [-s [-F] | -L | -P] [-f | -i] [-hnv] source_file ... target_dir
       link source_file target_file
make: *** [envtest] Error 1
```

**Comment by nirs** [comment]
@BenamarMk Thanks for testing! the issue should be fixed in current version.

**Comment by nirs** [comment]
> If the make file was not setting it, then fixing that is needed. I want to retain KUBEBUILDER_ASSETS explicit than hide the variable.

@ShyamsundarR handing of KUBEBUILDER_ASSETS is fixed by #772.

**Comment by nirs** [comment]
Closing for now, we still have ugly duplication in the test suites, but we can improve it later.

**Pull request closed without merging**
