### PR TITLE
Regenerate VRG manifest work on Hub recovery

### PR DESCRIPTION
**Pull request by ELENAGER**
We are handling here the case when Hub is recovering and we are in Initial Deploy flow (not Failover and not Relocate!).
We are assuming, that hub recovery does not delete the VRG on the managed cluster, but it's corresponding VRG manifest Work does not exist on the Hub.  

We will recreate MW for VRG, cached by drplacement controller from the managed cluster (using MCV). Replication state of MW for VRG recreation is also based on Spec read from the managed cluster.

### CODE REVIEW

**Review by BenamarMk — APPROVED** [review]
The overall changes look good to me. However, I have one suggestion for improvement, which is regarding the name of the function.

Additionally, I assume that you will make similar changes for Failover and Relocate in separate PRs. I am wondering if it is better to have only one PR with 3 commits instead of 3 PRs.

**Review by BenamarMk — APPROVED** [review]
LGTM

**Comment by ShyamsundarR** [comment]
@ELENAGER can we drop the merge commit, a rebase to main would be better than a merge, such that when we merge this PR the merge commit is not part of it.

**Comment by ELENAGER** [comment]
Closing this PR because of multiple merge commits. I opened another one: https://github.com/RamenDR/ramen/pull/892

**Pull request closed without merging**
