### PR TITLE
Improve demo env

### PR DESCRIPTION
**Pull request by nirs**
- Improve error message in test
- Disable curl progress in test
- Retry adding an ingress
- Wait until ingress has an ip address

### CODE REVIEW

**Comment by nirs** [comment]
Example start:

```
$ drenv start envs/demo.yaml 
2023-06-19 19:28:50,162 INFO    [demo] Starting environment
2023-06-19 19:28:50,236 INFO    [demo1] Starting minikube cluster
2023-06-19 19:28:51,273 INFO    [demo2] Starting minikube cluster
2023-06-19 19:30:09,307 INFO    [demo1] Cluster started in 79.07 seconds
2023-06-19 19:30:09,307 INFO    [demo1/0] Running addons/demo/start
2023-06-19 19:30:28,253 INFO    [demo2] Cluster started in 96.98 seconds
2023-06-19 19:30:28,254 INFO    [demo2/0] Running addons/demo/start
2023-06-19 19:31:10,142 INFO    [demo1/0] addons/demo/start completed in 60.83 seconds
2023-06-19 19:31:10,142 INFO    [demo1/0] Running addons/demo/test
2023-06-19 19:31:10,285 INFO    [demo1/0] addons/demo/test completed in 0.14 seconds
2023-06-19 19:31:29,197 INFO    [demo2/0] addons/demo/start completed in 60.94 seconds
2023-06-19 19:31:29,197 INFO    [demo2/0] Running addons/demo/test
2023-06-19 19:31:29,338 INFO    [demo2/0] addons/demo/test completed in 0.14 seconds
2023-06-19 19:31:29,338 INFO    [demo] Environment started in 159.18 seconds
```

**Comment by rakeshgm** [comment]
what is an interactive demo here? can you attach a few snapshots?

**Comment by nirs** [comment]
Example stop + start - slowe than delete + start but works.

```
$ drenv stop envs/demo.yaml 
2023-06-19 19:31:51,310 INFO    [demo] Stopping environment
2023-06-19 19:31:51,396 INFO    [demo2] Stopping cluster
2023-06-19 19:31:51,397 INFO    [demo1] Stopping cluster
2023-06-19 19:31:52,556 INFO    [demo1] Cluster stopped in 1.16 seconds
2023-06-19 19:31:57,606 INFO    [demo2] Cluster stopped in 6.21 seconds
2023-06-19 19:31:57,607 INFO    [demo] Environment stopped in 6.30 seconds
```

```
$ drenv start envs/demo.yaml 
2023-06-19 19:32:40,030 INFO    [demo] Starting environment
2023-06-19 19:32:40,152 INFO    [demo1] Starting minikube cluster
2023-06-19 19:32:44,290 INFO    [demo2] Starting minikube cluster
2023-06-19 19:33:56,543 INFO    [demo2] Cluster started in 72.25 seconds
2023-06-19 19:33:56,543 INFO    [demo2] Waiting until all deployments are available
2023-06-19 19:33:58,155 INFO    [demo1] Cluster started in 78.00 seconds
2023-06-19 19:33:58,155 INFO    [demo1] Waiting until all deployments are available
2023-06-19 19:34:40,463 INFO    [demo1] Deployments are available in 42.31 seconds
2023-06-19 19:34:40,464 INFO    [demo1/0] Running addons/demo/start
2023-06-19 19:35:35,913 INFO    [demo1/0] addons/demo/start completed in 55.45 seconds
2023-06-19 19:35:35,914 INFO    [demo1/0] Running addons/demo/test
2023-06-19 19:35:36,055 INFO    [demo1/0] addons/demo/test completed in 0.14 seconds
2023-06-19 19:35:51,054 INFO    [demo2] Deployments are available in 114.51 seconds
2023-06-19 19:35:51,055 INFO    [demo2/0] Running addons/demo/start
2023-06-19 19:36:29,923 INFO    [demo2/0] addons/demo/start completed in 38.87 seconds
2023-06-19 19:36:29,923 INFO    [demo2/0] Running addons/demo/test
2023-06-19 19:36:30,063 INFO    [demo2/0] addons/demo/test completed in 0.14 seconds
2023-06-19 19:36:30,064 INFO    [demo] Environment started in 230.03 seconds
```

Running with --verbose shows how time is spent - waiting until the ingress got
an ip address took about 60 seconds:

```
2023-06-19 19:40:15,433 INFO    [demo1/0] Running addons/demo/start
2023-06-19 19:40:15,492 DEBUG   [demo1/0] Deploying demo
2023-06-19 19:40:15,605 DEBUG   [demo1/0] deployment.apps/demo-deployment unchanged
2023-06-19 19:40:15,607 DEBUG   [demo1/0] Creating the service
2023-06-19 19:40:15,745 DEBUG   [demo1/0] service/demo-service unchanged
2023-06-19 19:40:15,748 DEBUG   [demo1/0] Waiting until deployment is rolled out
2023-06-19 19:40:15,799 DEBUG   [demo1/0] deployment "demo-deployment" successfully rolled out
2023-06-19 19:40:15,801 DEBUG   [demo1/0] Waiting until ingress controller deployment is rolled out
2023-06-19 19:40:15,843 DEBUG   [demo1/0] Configuring ingress
2023-06-19 19:40:15,843 DEBUG   [demo1/0] Attempt 1/5
2023-06-19 19:40:15,949 DEBUG   [demo1/0] ingress.networking.k8s.io/demo-ingress unchanged
2023-06-19 19:40:15,951 DEBUG   [demo1/0] Ingress configured (attempt 1/5)
2023-06-19 19:40:15,951 DEBUG   [demo1/0] Waiting until ingress is ready

2023-06-19 19:41:14,098 DEBUG   [demo1/0] ingress/demo-ingress exists
2023-06-19 19:41:14,106 INFO    [demo1/0] addons/demo/start completed in 58.67 seconds
2023-06-19 19:41:14,106 INFO    [demo1/0] Running addons/demo/test
2023-06-19 19:41:14,168 DEBUG   [demo1/0] ['addons/demo/test', 'demo1']
2023-06-19 19:41:14,168 DEBUG   [demo1/0] Testing demo deployment
2023-06-19 19:41:14,267 INFO    [demo1/0] addons/demo/test completed in 0.16 seconds
```

**Comment by nirs** [comment]
@rakeshgm the "interactive" part is not much so far - you can interact with the app using curl.

I think we can improve this later by replacing nginx with a custom web server providing
more interesting interactions that can be useful for testing dr. For example the application
can write data to storage on user request (e.g. counter + timestamp) and can report current
state via curl. With this we can check if failver/rellocate and inspect the state of the
app without accessing storage manually.

**Review by Shwetha-Acharya — APPROVED** [review]

**Review by rakeshgm — APPROVED** [review]

**Comment by nirs** [comment]
drenv tests are broken now in the CI, but this change is not related to drenv. Changes validated locally and not tested in the CI.

**Pull request merged**
