### PR TITLE
Validate managedclusteravailable before relocating

### PR DESCRIPTION
**Pull request by pruthvitd**
Code drop for
[Check and ensure managed cluster condition availability, before processing relocation #283](https://github.com/RamenDR/ramen/issues/283)

### CODE REVIEW

**Comment by BenamarMk** [comment]
I am not sure if this PR is necessary. The MCV is automatically updated every 30 seconds by default, though this interval can be adjusted using the `UpdateIntervalSeconds` setting in the `ViewScope`. Similarly, I believe the `ManagedCluster` follows a similar algorithm for condition updates. If that's the case, [this lightweight test](https://github.com/RamenDR/ramen/blob/546f89cc1bdce38dfb1275b2218083dac5964fd6/internal/controller/drplacementcontrol.go#L824) should suffice. Have we seen any issues that prompted this PR?  The one issue we had and fixed recently is [here](https://github.com/RamenDR/ramen/commit/791fef05dd35f32ee07f0e0f4a126f9554710328).

**Comment by pruthvitd** [comment]
> I am not sure if this PR is necessary. The MCV is automatically updated every 30 seconds by default, though this interval can be adjusted using the `UpdateIntervalSeconds` setting in the `ViewScope`. Similarly, I believe the `ManagedCluster` follows a similar algorithm for condition updates. If that's the case, [this lightweight test](https://github.com/RamenDR/ramen/blob/546f89cc1bdce38dfb1275b2218083dac5964fd6/internal/controller/drplacementcontrol.go#L824) should suffice. Have we seen any issues that prompted this PR? The one issue we had and fixed recently is [here](https://github.com/RamenDR/ramen/commit/791fef05dd35f32ee07f0e0f4a126f9554710328).

Hi @ShyamsundarR ,

Could you please confirm if this PR should be squashed as the fix that is being added to resolve the issue seem to have already been resolved with an alternative solution as mentioned by @BenamarMk. 

thanks,
Pruthvi

**Comment by ShyamsundarR** [comment]
@pruthvitd let's close this one, it should be handled via the MCV freshness as pointed out by @BenamarMk

**Comment by pruthvitd** [comment]
Closing the pull request as this fix is unnecessary as pointed out by [Benamer](https://github.com/RamenDR/ramen/pull/1667#issuecomment-2497867231)

**Pull request closed without merging**
