### PR TITLE
Introduce the ramenctl tool

### PR DESCRIPTION
**Pull request by nirs**
This tool replaces the scripts to deploy and configure ramen. We will add more commands needed for developing ramen later.

We start with README.md describing the tool behavior. The tool itself will be added in the next commits.

### CODE REVIEW

**Comment by nirs** [comment]
I discuss this in private chat with @ShyamsundarR:

- ramectl can be a problem if we want to include the commands later in the ramen krew plugin, you don't want to have `kubectgl ramenctl ...`
- The developer commands can be part of the krew plugin instead of a separate tool
- But our commands do not use the concept of `context` - our context is a cluster set
  of 3 clusters (hub, cluster1, cluster2), so these commands are not a good match for a kubctl plugin.
- Same issue may exist in other user level commands we plan
- We have more urgent things so we should keep this simple and quick

**Comment by nirs** [comment]
Github is up now but it does not show all the pushed commits yet, we should have:

```
3b7d495 Implement `ramenctl unconfig`
971a0f9 Implement `ramenctl config`
15d7903 Add command module
79ec43d Implement 'ramenctl deploy' command
1288cc3 Add setup.py
2422b64 Add basic tool infrastructure
c186b86 Start the ramenctl tool
```

**Comment by nirs** [comment]
Example run with --verbose:

```
$ ramenctl deploy -v; ramenctl config regional-dr -v; ramenctl unconfig regional-dr -v; ramenctl undeploy -v
2023-05-15 16:39:39,325 DEBUG   [ramenctl] Running with arguments Namespace(verbose=True, command=<function run at 0x7ffb1c7759e0>, hub_name='hub', clusters_names=['dr1', 'dr2'], source_dir='.', image='quay.io/ramendr/ramen-operator:latest')
2023-05-15 16:39:39,325 INFO    [ramenctl] Deploying Ramen operator
2023-05-15 16:39:39,325 INFO    [ramenctl] Saving image 'quay.io/ramendr/ramen-operator:latest'
2023-05-15 16:39:41,301 INFO    [ramenctl] Loading image in cluster 'hub'
2023-05-15 16:39:41,301 INFO    [ramenctl] Loading image in cluster 'dr1'
2023-05-15 16:39:41,302 INFO    [ramenctl] Loading image in cluster 'dr2'
2023-05-15 16:39:48,719 INFO    [ramenctl] Deploying ramen operator in cluster 'hub'
2023-05-15 16:39:48,765 DEBUG   [ramenctl] Switched to context "hub".
2023-05-15 16:39:48,770 DEBUG   [ramenctl] make: Entering directory '/home/nsoffer/src/ramen'
2023-05-15 16:39:48,902 DEBUG   [ramenctl] /home/nsoffer/src/ramen/bin/controller-gen rbac:roleName=operator-role crd:generateEmbeddedObjectMeta=true webhook paths="./..." output:crd:artifacts:config=config/crd/bases
2023-05-15 16:39:50,858 DEBUG   [ramenctl] cd config/hub/default/k8s && /home/nsoffer/src/ramen/bin/kustomize edit set image kube-rbac-proxy="gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0"
2023-05-15 16:39:50,882 DEBUG   [ramenctl] cd config/hub/manager && /home/nsoffer/src/ramen/bin/kustomize edit set image controller=quay.io/ramendr/ramen-operator:latest
2023-05-15 16:39:50,897 DEBUG   [ramenctl] /home/nsoffer/src/ramen/bin/kustomize build --load-restrictor LoadRestrictionsNone config/hub/default/k8s | kubectl apply -f -
2023-05-15 16:39:52,332 DEBUG   [ramenctl] namespace/ramen-system created
2023-05-15 16:39:52,356 DEBUG   [ramenctl] customresourcedefinition.apiextensions.k8s.io/drclusters.ramendr.openshift.io created
2023-05-15 16:39:52,396 DEBUG   [ramenctl] customresourcedefinition.apiextensions.k8s.io/drplacementcontrols.ramendr.openshift.io created
2023-05-15 16:39:52,439 DEBUG   [ramenctl] customresourcedefinition.apiextensions.k8s.io/drpolicies.ramendr.openshift.io created
2023-05-15 16:39:52,466 DEBUG   [ramenctl] serviceaccount/ramen-hub-operator created
2023-05-15 16:39:52,488 DEBUG   [ramenctl] role.rbac.authorization.k8s.io/ramen-hub-leader-election-role created
2023-05-15 16:39:52,503 DEBUG   [ramenctl] role.rbac.authorization.k8s.io/ramen-hub-metrics created
2023-05-15 16:39:52,517 DEBUG   [ramenctl] role.rbac.authorization.k8s.io/ramen-hub-operator-role created
2023-05-15 16:39:52,526 DEBUG   [ramenctl] clusterrole.rbac.authorization.k8s.io/ramen-hub-metrics-reader created
2023-05-15 16:39:52,535 DEBUG   [ramenctl] clusterrole.rbac.authorization.k8s.io/ramen-hub-operator-role created
2023-05-15 16:39:52,546 DEBUG   [ramenctl] clusterrole.rbac.authorization.k8s.io/ramen-hub-proxy-role created
2023-05-15 16:39:52,559 DEBUG   [ramenctl] rolebinding.rbac.authorization.k8s.io/ramen-hub-leader-election-rolebinding created
2023-05-15 16:39:52,567 DEBUG   [ramenctl] rolebinding.rbac.authorization.k8s.io/ramen-hub-operator-rolebinding created
2023-05-15 16:39:52,575 DEBUG   [ramenctl] clusterrolebinding.rbac.authorization.k8s.io/ramen-hub-operator-rolebinding created
2023-05-15 16:39:52,587 DEBUG   [ramenctl] clusterrolebinding.rbac.authorization.k8s.io/ramen-hub-proxy-rolebinding created
2023-05-15 16:39:52,597 DEBUG   [ramenctl] configmap/ramen-hub-operator-config created
2023-05-15 16:39:52,616 DEBUG   [ramenctl] service/ramen-hub-operator-metrics-service created
2023-05-15 16:39:52,649 DEBUG   [ramenctl] service/ramen-hub-webhook-service created
2023-05-15 16:39:52,669 DEBUG   [ramenctl] deployment.apps/ramen-hub-operator created
2023-05-15 16:39:52,721 DEBUG   [ramenctl] certificate.cert-manager.io/ramen-hub-serving-cert created
2023-05-15 16:39:52,770 DEBUG   [ramenctl] issuer.cert-manager.io/ramen-hub-selfsigned-issuer created
2023-05-15 16:39:52,806 DEBUG   [ramenctl] validatingwebhookconfiguration.admissionregistration.k8s.io/ramen-hub-validating-webhook-configuration created
2023-05-15 16:39:52,816 DEBUG   [ramenctl] make: Leaving directory '/home/nsoffer/src/ramen'
2023-05-15 16:39:52,816 INFO    [ramenctl] Deploying ramen operator in cluster 'dr1'
2023-05-15 16:39:52,867 DEBUG   [ramenctl] Switched to context "dr1".
2023-05-15 16:39:52,872 DEBUG   [ramenctl] make: Entering directory '/home/nsoffer/src/ramen'
2023-05-15 16:39:52,976 DEBUG   [ramenctl] /home/nsoffer/src/ramen/bin/controller-gen rbac:roleName=operator-role crd:generateEmbeddedObjectMeta=true webhook paths="./..." output:crd:artifacts:config=config/crd/bases
2023-05-15 16:39:55,071 DEBUG   [ramenctl] cd config/dr-cluster/default && /home/nsoffer/src/ramen/bin/kustomize edit set image kube-rbac-proxy="gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0"
2023-05-15 16:39:55,087 DEBUG   [ramenctl] cd config/dr-cluster/manager && /home/nsoffer/src/ramen/bin/kustomize edit set image controller=quay.io/ramendr/ramen-operator:latest;\
2023-05-15 16:39:55,087 DEBUG   [ramenctl] if (false);then printf 'kubeObjectProtection:\n  disabled: true\n'>>ramen_manager_config.yaml;fi
2023-05-15 16:39:55,103 DEBUG   [ramenctl] /home/nsoffer/src/ramen/bin/kustomize build --load-restrictor LoadRestrictionsNone config/dr-cluster/default | kubectl apply -f -
2023-05-15 16:39:56,515 DEBUG   [ramenctl] namespace/ramen-system created
2023-05-15 16:39:56,544 DEBUG   [ramenctl] customresourcedefinition.apiextensions.k8s.io/maintenancemodes.ramendr.openshift.io created
2023-05-15 16:39:56,588 DEBUG   [ramenctl] customresourcedefinition.apiextensions.k8s.io/protectedvolumereplicationgrouplists.ramendr.openshift.io created
2023-05-15 16:39:56,635 DEBUG   [ramenctl] customresourcedefinition.apiextensions.k8s.io/volumereplicationgroups.ramendr.openshift.io created
2023-05-15 16:39:56,783 DEBUG   [ramenctl] serviceaccount/ramen-dr-cluster-operator created
2023-05-15 16:39:56,895 DEBUG   [ramenctl] role.rbac.authorization.k8s.io/ramen-dr-cluster-leader-election-role created
2023-05-15 16:39:56,929 DEBUG   [ramenctl] role.rbac.authorization.k8s.io/ramen-dr-cluster-operator-role created
2023-05-15 16:39:56,956 DEBUG   [ramenctl] clusterrole.rbac.authorization.k8s.io/ramen-dr-cluster-metrics-reader created
2023-05-15 16:39:56,996 DEBUG   [ramenctl] clusterrole.rbac.authorization.k8s.io/ramen-dr-cluster-operator-role created
2023-05-15 16:39:57,028 DEBUG   [ramenctl] clusterrole.rbac.authorization.k8s.io/ramen-dr-cluster-proxy-role created
2023-05-15 16:39:57,068 DEBUG   [ramenctl] rolebinding.rbac.authorization.k8s.io/ramen-dr-cluster-leader-election-rolebinding created
2023-05-15 16:39:57,081 DEBUG   [ramenctl] rolebinding.rbac.authorization.k8s.io/ramen-dr-cluster-operator-rolebinding created
2023-05-15 16:39:57,089 DEBUG   [ramenctl] clusterrolebinding.rbac.authorization.k8s.io/ramen-dr-cluster-operator-rolebinding created
2023-05-15 16:39:57,101 DEBUG   [ramenctl] clusterrolebinding.rbac.authorization.k8s.io/ramen-dr-cluster-proxy-rolebinding created
2023-05-15 16:39:57,123 DEBUG   [ramenctl] configmap/ramen-dr-cluster-operator-config created
2023-05-15 16:39:57,151 DEBUG   [ramenctl] service/ramen-dr-cluster-operator-metrics-service created
2023-05-15 16:39:57,183 DEBUG   [ramenctl] deployment.apps/ramen-dr-cluster-operator created
2023-05-15 16:39:57,191 DEBUG   [ramenctl] make: Leaving directory '/home/nsoffer/src/ramen'
2023-05-15 16:39:57,192 INFO    [ramenctl] Deploying ramen operator in cluster 'dr2'
2023-05-15 16:39:57,247 DEBUG   [ramenctl] Switched to context "dr2".
2023-05-15 16:39:57,252 DEBUG   [ramenctl] make: Entering directory '/home/nsoffer/src/ramen'
2023-05-15 16:39:57,365 DEBUG   [ramenctl] /home/nsoffer/src/ramen/bin/controller-gen rbac:roleName=operator-role crd:generateEmbeddedObjectMeta=true webhook paths="./..." output:crd:artifacts:config=config/crd/bases
2023-05-15 16:39:59,256 DEBUG   [ramenctl] cd config/dr-cluster/default && /home/nsoffer/src/ramen/bin/kustomize edit set image kube-rbac-proxy="gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0"
2023-05-15 16:39:59,273 DEBUG   [ramenctl] cd config/dr-cluster/manager && /home/nsoffer/src/ramen/bin/kustomize edit set image controller=quay.io/ramendr/ramen-operator:latest;\
2023-05-15 16:39:59,273 DEBUG   [ramenctl] if (false);then printf 'kubeObjectProtection:\n  disabled: true\n'>>ramen_manager_config.yaml;fi
2023-05-15 16:39:59,292 DEBUG   [ramenctl] /home/nsoffer/src/ramen/bin/kustomize build --load-restrictor LoadRestrictionsNone config/dr-cluster/default | kubectl apply -f -
2023-05-15 16:40:00,713 DEBUG   [ramenctl] namespace/ramen-system created
2023-05-15 16:40:00,734 DEBUG   [ramenctl] customresourcedefinition.apiextensions.k8s.io/maintenancemodes.ramendr.openshift.io created
2023-05-15 16:40:00,767 DEBUG   [ramenctl] customresourcedefinition.apiextensions.k8s.io/protectedvolumereplicationgrouplists.ramendr.openshift.io created
2023-05-15 16:40:00,840 DEBUG   [ramenctl] customresourcedefinition.apiextensions.k8s.io/volumereplicationgroups.ramendr.openshift.io created
2023-05-15 16:40:00,914 DEBUG   [ramenctl] serviceaccount/ramen-dr-cluster-operator created
2023-05-15 16:40:00,970 DEBUG   [ramenctl] role.rbac.authorization.k8s.io/ramen-dr-cluster-leader-election-role created
2023-05-15 16:40:00,986 DEBUG   [ramenctl] role.rbac.authorization.k8s.io/ramen-dr-cluster-operator-role created
2023-05-15 16:40:00,999 DEBUG   [ramenctl] clusterrole.rbac.authorization.k8s.io/ramen-dr-cluster-metrics-reader created
2023-05-15 16:40:01,013 DEBUG   [ramenctl] clusterrole.rbac.authorization.k8s.io/ramen-dr-cluster-operator-role created
2023-05-15 16:40:01,034 DEBUG   [ramenctl] clusterrole.rbac.authorization.k8s.io/ramen-dr-cluster-proxy-role created
2023-05-15 16:40:01,046 DEBUG   [ramenctl] rolebinding.rbac.authorization.k8s.io/ramen-dr-cluster-leader-election-rolebinding created
2023-05-15 16:40:01,062 DEBUG   [ramenctl] rolebinding.rbac.authorization.k8s.io/ramen-dr-cluster-operator-rolebinding created
2023-05-15 16:40:01,071 DEBUG   [ramenctl] clusterrolebinding.rbac.authorization.k8s.io/ramen-dr-cluster-operator-rolebinding created
2023-05-15 16:40:01,087 DEBUG   [ramenctl] clusterrolebinding.rbac.authorization.k8s.io/ramen-dr-cluster-proxy-rolebinding created
2023-05-15 16:40:01,101 DEBUG   [ramenctl] configmap/ramen-dr-cluster-operator-config created
2023-05-15 16:40:01,134 DEBUG   [ramenctl] service/ramen-dr-cluster-operator-metrics-service created
2023-05-15 16:40:01,163 DEBUG   [ramenctl] deployment.apps/ramen-dr-cluster-operator created
2023-05-15 16:40:01,171 DEBUG   [ramenctl] make: Leaving directory '/home/nsoffer/src/ramen'
2023-05-15 16:40:01,171 INFO    [ramenctl] Ramen operator was deployed successfuly
2023-05-15 16:40:01,307 DEBUG   [ramenctl] Running with arguments Namespace(verbose=True, command=<function run at 0x7f532ee62de0>, hub_name='hub', clusters_names=['dr1', 'dr2'], ramen_namespace='ramen-system', env_type='regional-dr')
2023-05-15 16:40:01,307 INFO    [ramenctl] Configuring ramen for regional-dr
2023-05-15 16:40:01,307 INFO    [ramenctl] Waiting until ramen-hub-operator is rolled out
2023-05-15 16:40:01,388 DEBUG   [ramenctl] Waiting for deployment "ramen-hub-operator" rollout to finish: 0 of 1 updated replicas are available...
2023-05-15 16:40:03,683 DEBUG   [ramenctl] deployment "ramen-hub-operator" successfully rolled out
2023-05-15 16:40:03,686 INFO    [ramenctl] Creating s3 secret in ramen hub namespace
2023-05-15 16:40:04,945 DEBUG   [ramenctl] secret/s3secret created
2023-05-15 16:40:04,950 INFO    [ramenctl] Updating ramen config map
2023-05-15 16:40:05,435 DEBUG   [ramenctl] configmap/ramen-hub-operator-config configured
2023-05-15 16:40:05,440 INFO    [ramenctl] Creating DRClusters and DRPolicy for regional-dr
2023-05-15 16:40:05,803 DEBUG   [ramenctl] drcluster.ramendr.openshift.io/dr1 created
2023-05-15 16:40:05,816 DEBUG   [ramenctl] drcluster.ramendr.openshift.io/dr2 created
2023-05-15 16:40:05,828 DEBUG   [ramenctl] drpolicy.ramendr.openshift.io/dr-policy created
2023-05-15 16:40:05,833 INFO    [ramenctl] Waiting until DRClusters report phase
2023-05-15 16:40:06,964 DEBUG   [ramenctl] drcluster/dr1 exists
2023-05-15 16:40:07,038 DEBUG   [ramenctl] drcluster/dr2 exists
2023-05-15 16:40:07,039 INFO    [ramenctl] Waiting until DRClusters phase is available
2023-05-15 16:40:07,207 DEBUG   [ramenctl] drcluster.ramendr.openshift.io/dr1 condition met
2023-05-15 16:40:07,309 DEBUG   [ramenctl] drcluster.ramendr.openshift.io/dr2 condition met
2023-05-15 16:40:07,312 INFO    [ramenctl] Waiting until DRPolicy is validated
2023-05-15 16:40:07,474 DEBUG   [ramenctl] drpolicy.ramendr.openshift.io/dr-policy condition met
2023-05-15 16:40:07,477 INFO    [ramenctl] Creating channel
2023-05-15 16:40:07,760 DEBUG   [ramenctl] namespace/ramen-samples created
2023-05-15 16:40:07,808 DEBUG   [ramenctl] channel.apps.open-cluster-management.io/ramen-gitops created
2023-05-15 16:40:07,818 INFO    [ramenctl] Ramen was configured successfully
2023-05-15 16:40:07,961 DEBUG   [ramenctl] Running with arguments Namespace(verbose=True, command=<function run at 0x7f278705efc0>, hub_name='hub', clusters_names=['dr1', 'dr2'], ramen_namespace='ramen-system', env_type='regional-dr')
2023-05-15 16:40:07,961 INFO    [ramenctl] Unconfiguring Ramen for regional-dr
2023-05-15 16:40:07,961 INFO    [ramenctl] Deleting samples channel
2023-05-15 16:40:08,025 DEBUG   [ramenctl] namespace "ramen-samples" deleted
2023-05-15 16:40:08,039 DEBUG   [ramenctl] channel.apps.open-cluster-management.io "ramen-gitops" deleted
2023-05-15 16:40:13,276 INFO    [ramenctl] Deleting DRClusters and DRPolicy
2023-05-15 16:40:13,411 DEBUG   [ramenctl] drcluster.ramendr.openshift.io "dr1" deleted
2023-05-15 16:40:13,426 DEBUG   [ramenctl] drcluster.ramendr.openshift.io "dr2" deleted
2023-05-15 16:40:13,435 DEBUG   [ramenctl] drpolicy.ramendr.openshift.io "dr-policy" deleted
2023-05-15 16:40:13,812 INFO    [ramenctl] Deleting s3 secret in ramen hub namespace
2023-05-15 16:40:13,897 DEBUG   [ramenctl] secret "s3secret" deleted
2023-05-15 16:40:13,902 INFO    [ramenctl] Ramen was unconfigured successfully
2023-05-15 16:40:14,046 DEBUG   [ramenctl] Running with arguments Namespace(verbose=True, command=<function run at 0x7f0ac2c5ab60>, hub_name='hub', clusters_names=['dr1', 'dr2'], source_dir='.')
2023-05-15 16:40:14,046 INFO    [ramenctl] Undeploying ramen operator
2023-05-15 16:40:14,047 INFO    [ramenctl] Undeploying ramen operator in cluster 'dr1'
2023-05-15 16:40:14,098 DEBUG   [ramenctl] Switched to context "dr1".
2023-05-15 16:40:14,103 DEBUG   [ramenctl] make: Entering directory '/home/nsoffer/src/ramen'
2023-05-15 16:40:14,202 DEBUG   [ramenctl] /home/nsoffer/src/ramen/bin/kustomize build --load-restrictor LoadRestrictionsNone config/dr-cluster/default | kubectl delete -f - --ignore-not-found
2023-05-15 16:40:14,391 DEBUG   [ramenctl] namespace "ramen-system" deleted
2023-05-15 16:40:14,410 DEBUG   [ramenctl] customresourcedefinition.apiextensions.k8s.io "maintenancemodes.ramendr.openshift.io" deleted
2023-05-15 16:40:14,453 DEBUG   [ramenctl] customresourcedefinition.apiextensions.k8s.io "protectedvolumereplicationgrouplists.ramendr.openshift.io" deleted
2023-05-15 16:40:14,500 DEBUG   [ramenctl] customresourcedefinition.apiextensions.k8s.io "volumereplicationgroups.ramendr.openshift.io" deleted
2023-05-15 16:40:14,547 DEBUG   [ramenctl] serviceaccount "ramen-dr-cluster-operator" deleted
2023-05-15 16:40:14,580 DEBUG   [ramenctl] role.rbac.authorization.k8s.io "ramen-dr-cluster-leader-election-role" deleted
2023-05-15 16:40:14,589 DEBUG   [ramenctl] role.rbac.authorization.k8s.io "ramen-dr-cluster-operator-role" deleted
2023-05-15 16:40:14,603 DEBUG   [ramenctl] clusterrole.rbac.authorization.k8s.io "ramen-dr-cluster-metrics-reader" deleted
2023-05-15 16:40:14,617 DEBUG   [ramenctl] clusterrole.rbac.authorization.k8s.io "ramen-dr-cluster-operator-role" deleted
2023-05-15 16:40:14,629 DEBUG   [ramenctl] clusterrole.rbac.authorization.k8s.io "ramen-dr-cluster-proxy-role" deleted
2023-05-15 16:40:14,635 DEBUG   [ramenctl] rolebinding.rbac.authorization.k8s.io "ramen-dr-cluster-leader-election-rolebinding" deleted
2023-05-15 16:40:14,645 DEBUG   [ramenctl] rolebinding.rbac.authorization.k8s.io "ramen-dr-cluster-operator-rolebinding" deleted
2023-05-15 16:40:14,651 DEBUG   [ramenctl] clusterrolebinding.rbac.authorization.k8s.io "ramen-dr-cluster-operator-rolebinding" deleted
2023-05-15 16:40:14,658 DEBUG   [ramenctl] clusterrolebinding.rbac.authorization.k8s.io "ramen-dr-cluster-proxy-rolebinding" deleted
2023-05-15 16:40:14,719 DEBUG   [ramenctl] service "ramen-dr-cluster-operator-metrics-service" deleted
2023-05-15 16:40:14,733 DEBUG   [ramenctl] deployment.apps "ramen-dr-cluster-operator" deleted
2023-05-15 16:40:20,465 DEBUG   [ramenctl] make: Leaving directory '/home/nsoffer/src/ramen'
2023-05-15 16:40:20,465 INFO    [ramenctl] Undeploying ramen operator in cluster 'dr2'
2023-05-15 16:40:20,516 DEBUG   [ramenctl] Switched to context "dr2".
2023-05-15 16:40:20,526 DEBUG   [ramenctl] make: Entering directory '/home/nsoffer/src/ramen'
2023-05-15 16:40:20,632 DEBUG   [ramenctl] /home/nsoffer/src/ramen/bin/kustomize build --load-restrictor LoadRestrictionsNone config/dr-cluster/default | kubectl delete -f - --ignore-not-found
2023-05-15 16:40:20,810 DEBUG   [ramenctl] namespace "ramen-system" deleted
2023-05-15 16:40:20,820 DEBUG   [ramenctl] customresourcedefinition.apiextensions.k8s.io "maintenancemodes.ramendr.openshift.io" deleted
2023-05-15 16:40:20,864 DEBUG   [ramenctl] customresourcedefinition.apiextensions.k8s.io "protectedvolumereplicationgrouplists.ramendr.openshift.io" deleted
2023-05-15 16:40:20,897 DEBUG   [ramenctl] customresourcedefinition.apiextensions.k8s.io "volumereplicationgroups.ramendr.openshift.io" deleted
2023-05-15 16:40:20,990 DEBUG   [ramenctl] clusterrole.rbac.authorization.k8s.io "ramen-dr-cluster-metrics-reader" deleted
2023-05-15 16:40:21,017 DEBUG   [ramenctl] clusterrole.rbac.authorization.k8s.io "ramen-dr-cluster-operator-role" deleted
2023-05-15 16:40:21,034 DEBUG   [ramenctl] clusterrole.rbac.authorization.k8s.io "ramen-dr-cluster-proxy-role" deleted
2023-05-15 16:40:21,048 DEBUG   [ramenctl] clusterrolebinding.rbac.authorization.k8s.io "ramen-dr-cluster-operator-rolebinding" deleted
2023-05-15 16:40:21,057 DEBUG   [ramenctl] clusterrolebinding.rbac.authorization.k8s.io "ramen-dr-cluster-proxy-rolebinding" deleted
2023-05-15 16:40:25,987 DEBUG   [ramenctl] make: Leaving directory '/home/nsoffer/src/ramen'
2023-05-15 16:40:25,987 INFO    [ramenctl] Undeploying ramen operator in cluster 'hub'
2023-05-15 16:40:26,040 DEBUG   [ramenctl] Switched to context "hub".
2023-05-15 16:40:26,047 DEBUG   [ramenctl] make: Entering directory '/home/nsoffer/src/ramen'
2023-05-15 16:40:26,152 DEBUG   [ramenctl] /home/nsoffer/src/ramen/bin/kustomize build --load-restrictor LoadRestrictionsNone config/hub/default/k8s | kubectl delete -f - --ignore-not-found
2023-05-15 16:40:26,353 DEBUG   [ramenctl] namespace "ramen-system" deleted
2023-05-15 16:40:26,367 DEBUG   [ramenctl] customresourcedefinition.apiextensions.k8s.io "drclusters.ramendr.openshift.io" deleted
2023-05-15 16:40:26,405 DEBUG   [ramenctl] customresourcedefinition.apiextensions.k8s.io "drplacementcontrols.ramendr.openshift.io" deleted
2023-05-15 16:40:26,442 DEBUG   [ramenctl] customresourcedefinition.apiextensions.k8s.io "drpolicies.ramendr.openshift.io" deleted
2023-05-15 16:40:26,469 DEBUG   [ramenctl] serviceaccount "ramen-hub-operator" deleted
2023-05-15 16:40:26,494 DEBUG   [ramenctl] role.rbac.authorization.k8s.io "ramen-hub-leader-election-role" deleted
2023-05-15 16:40:26,502 DEBUG   [ramenctl] role.rbac.authorization.k8s.io "ramen-hub-metrics" deleted
2023-05-15 16:40:26,526 DEBUG   [ramenctl] role.rbac.authorization.k8s.io "ramen-hub-operator-role" deleted
2023-05-15 16:40:26,536 DEBUG   [ramenctl] clusterrole.rbac.authorization.k8s.io "ramen-hub-metrics-reader" deleted
2023-05-15 16:40:26,544 DEBUG   [ramenctl] clusterrole.rbac.authorization.k8s.io "ramen-hub-operator-role" deleted
2023-05-15 16:40:26,552 DEBUG   [ramenctl] clusterrole.rbac.authorization.k8s.io "ramen-hub-proxy-role" deleted
2023-05-15 16:40:26,560 DEBUG   [ramenctl] rolebinding.rbac.authorization.k8s.io "ramen-hub-leader-election-rolebinding" deleted
2023-05-15 16:40:26,566 DEBUG   [ramenctl] rolebinding.rbac.authorization.k8s.io "ramen-hub-operator-rolebinding" deleted
2023-05-15 16:40:26,574 DEBUG   [ramenctl] clusterrolebinding.rbac.authorization.k8s.io "ramen-hub-operator-rolebinding" deleted
2023-05-15 16:40:26,585 DEBUG   [ramenctl] clusterrolebinding.rbac.authorization.k8s.io "ramen-hub-proxy-rolebinding" deleted
2023-05-15 16:40:26,596 DEBUG   [ramenctl] configmap "ramen-hub-operator-config" deleted
2023-05-15 16:40:26,622 DEBUG   [ramenctl] service "ramen-hub-operator-metrics-service" deleted
2023-05-15 16:40:26,655 DEBUG   [ramenctl] service "ramen-hub-webhook-service" deleted
2023-05-15 16:40:26,662 DEBUG   [ramenctl] deployment.apps "ramen-hub-operator" deleted
2023-05-15 16:40:26,670 DEBUG   [ramenctl] certificate.cert-manager.io "ramen-hub-serving-cert" deleted
2023-05-15 16:40:26,691 DEBUG   [ramenctl] issuer.cert-manager.io "ramen-hub-selfsigned-issuer" deleted
2023-05-15 16:40:26,720 DEBUG   [ramenctl] validatingwebhookconfiguration.admissionregistration.k8s.io "ramen-hub-validating-webhook-configuration" deleted
2023-05-15 16:40:33,944 DEBUG   [ramenctl] make: Leaving directory '/home/nsoffer/src/ramen'
2023-05-15 16:40:33,945 INFO    [ramenctl] Ramen operator was undeployed successfuly
```

**Review by BenamarMk — APPROVED** [review]

**Comment by rakeshgm** [comment]
I have tried the basic deployment from the updated devel-quick-start. And I am able to deploy ramen. Hence approving the PR

**Review by rakeshgm — APPROVED** [review]

**Pull request merged**
