### PR TITLE
Upgrade submariner version to 0.17.0

### PR DESCRIPTION
**Pull request by Sheetalpamecha**
Fixes: #1263
Signed-off-by: Sheetal Pamecha <spamecha@redhat.com>

### CODE REVIEW

**Review by nirs — COMMENTED** [review]
Thanks @Sheetalpamecha! the change looks good, we need to update also these docs that subctl 0.17.0 is required:
- docs/user-quick-start.md
- test/README.md

And finally test that starting an environment still works. The quick way to test it is using the submariner test environment:

```
cd test
drenv start envs/submariner.yaml
```

For the CI we may need to update the CI machine to install new subctl version so builds pass with this change.

**Comment by nirs** [comment]
@Sheetalpamecha I will test this next week.

**Comment by Sheetalpamecha** [comment]
> @Sheetalpamecha I will test this next week.

Hi @nirs, I was also trying to test but encountered some errors in my machine during setup. Hopefully It will be done in weekend. Will update in this thread with my progress.

**Comment by nirs** [comment]
> > @Sheetalpamecha I will test this next week.
> 
> Hi @nirs, I was also trying to test but encountered some errors in my machine during setup. Hopefully It will be done in weekend. Will update in this thread with my progress.

I have a stress test setup ready, so I can test this now. It will help if you add the missing docs updates I mentioned in https://github.com/RamenDR/ramen/pull/1274#pullrequestreview-1948885563

**Comment by nirs** [comment]
I run stress test:
- 200 runs with submariner.yaml - 100% passed
- 100 runs with regional-dr.yaml - 100% passed

Also run basic-test once with deployemnt rbd, it should not be affected by this change.

**Review by nirs — APPROVED** [review]

**Comment by nirs** [comment]
@Sheetalpamecha thanks! you can look for more issue here: https://github.com/RamenDR/ramen/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

**Pull request merged**
