### PR TITLE
Define local API version for PreferredDecision

### LINKED ISSUE #1343: Change DRPC.Status.PreferredDecision type to a generic {ClusterName/Namespace} to remove the multicloud-operators-placementrule dependency from API go.mod
Currently the API go.mod imports [multicloud-operators-placementrule](https://github.com/RamenDR/ramen/blob/1df40b31bde0a2f9cce7772411104ecd9c6286df/api/go.mod#L6). This is because the status.PreferredDecision is leveraging the type `PlacementDecision`

To enable a cleaner go.mod for the APIs that other modules may import, we could change this to a local struct instead of leveraging the PlacementDecision from the said import.

### PR DESCRIPTION
**Pull request by ShyamsundarR**
This helps remove the dependency on multicloud-operators-placementrule dependency in go.mod. Enabling a more cleaner module for dependent components to import and use.

Fixes #1343

### CODE REVIEW

**Review by nirs — APPROVED** [review]
Looks good, I'm not sure this will not break client code assuming  `github.com/stolostron/multicloud-operators-placementrule/pkg/apis/apps/v1.PlacementDecision`, but if this break this will be a compile error which is easy to fix and getting rid of the horrible dependencies in the API is great!

**Comment by raghavendra-talur** [comment]
The change looks mostly safe to me.

If there is any consumer of DRPC status which is using an older version of the Ramen API, would they get an error or will the unmarshal happen seamlessly, I am not sure.

Another thing to check for is what happens in the upgrade path. Will the API server transition that status properly once the CRD is updated.

The json tags are the same so JSON to GO and vice-versa should be fine.

@ShyamsundarR If you can test a upgrade scenario that would be good. LGTM!

**Review by raghavendra-talur — APPROVED** [review]

**Comment by ShyamsundarR** [comment]
> The change looks mostly safe to me.
> 
> If there is any consumer of DRPC status which is using an older version of the Ramen API, would they get an error or will the unmarshal happen seamlessly, I am not sure.
> 
> Another thing to check for is what happens in the upgrade path. Will the API server transition that status properly once the CRD is updated.
> 
> The json tags are the same so JSON to GO and vice-versa should be fine.
> 
> @ShyamsundarR If you can test a upgrade scenario that would be good. LGTM!

Upgrade using a DRPC from an older image to the newer image and CRD spec tested, and passed.

**Comment by raghavendra-talur** [comment]
> > The change looks mostly safe to me.
> > If there is any consumer of DRPC status which is using an older version of the Ramen API, would they get an error or will the unmarshal happen seamlessly, I am not sure.
> > Another thing to check for is what happens in the upgrade path. Will the API server transition that status properly once the CRD is updated.
> > The json tags are the same so JSON to GO and vice-versa should be fine.
> > @ShyamsundarR If you can test a upgrade scenario that would be good. LGTM!
> 
> Upgrade using a DRPC from an older image to the newer image and CRD spec tested, and passed.

Thanks!

**Pull request merged**
