### PR TITLE
Optimize drenv for CI lab

### LINKED ISSUE #1295: Timeout in DNS lookup in submariner test
Sometimes we see this random failure in submariner test:

```
      drenv.commands.Error: Command failed:
         command: ('kubectl', 'exec', '--context', 'dr2', 'test',
                 '--namespace=ns1', '--', 'curl', '--no-progress-meter',
                 'nginx.ns1.svc.clusterset.local')
         exitcode: 6
         error:
            curl: (6) Could not resolve host: nginx.ns1.svc.clusterset.local
            command terminated with exit code 6
```

We know that the first lookup can take about 80 seconds (based on a comment in the code). We use timeout of 120 seconds - maybe we need bigger timeout to handle special cases?

### LINKED ISSUE #1296: Timeout waiting for nginx deployment in submariner test
Sometimes we see this random error in submariner test:

```
        drenv.commands.Error: Command failed:
           command: ('addons/submariner/test', 'hub', 'dr1', 'dr2')
           exitcode: 1
           error:
              Traceback (most recent call last):
                ...
              drenv.commands.Error: Command failed:
                 command: ('kubectl', 'wait', '--context', 'dr1',
                         'deploy/nginx', '--for=condition=Available',
                         '--namespace=ns1', '--timeout=120s')
                 exitcode: 1
                 error:
                    error: timed out waiting for the condition on deployments/nginx
```

We wait for nginx deployemnt using 17.5m image using 120 seconds timeout. This works fine locally with good network but maybe it is not enough for the e2e lab flaky network.

### PR DESCRIPTION
**Pull request by nirs**
Optimize drenv for faster and more reliable builds in the CI lab.

- Increase number of cpus in the managed clusters
- Minimize timeouts for faster failures, so retries will start faster
- Increase specific timeouts that proved to be too short, preventing slow retry.
- Fix the way we wait for managedcluster after joining a managed cluster to the hub.

Tested on bare metal machine in the CI lab on libvirt vm on our new bare metal server.

Tested on top of:

- #1267 
- #1303
- #1302 
- #1301 
- #1300
- #1267 
- #1299 
- #1291
- #1319
- #1320
- #1321

Last runs stats:

```
$ stress-test/run -r 50 envs/regional-dr.yaml 
[50/50] 50 passed, 0 failed, rate: 100.0%, time/run: 547.6s
```

Fixes #1295 
Fixes #1296

### CODE REVIEW

**Comment by nirs** [comment]
I don't see ocm-controller failure, but this error becomes more common. We need to debug this on the cluster, maybe some component is failing to get an image.

```
drenv.commands.Error: Command failed:
   command: ('addons/ocm-cluster/start', 'rdr-dr1', 'rdr-hub')
   exitcode: 1
   error:
      Traceback (most recent call last):
        File "/home/github/actions-runner/_work/ramen/ramen/test/addons/ocm-cluster/start", line 135, in <module>
          deploy(cluster_name, hub_name)
        File "/home/github/actions-runner/_work/ramen/ramen/test/addons/ocm-cluster/start", line 47, in deploy
          wait_for_managed_cluster(cluster, hub)
        File "/home/github/actions-runner/_work/ramen/ramen/test/addons/ocm-cluster/start", line 113, in wait_for_managed_cluster
          kubectl.wait(
        File "/home/github/actions-runner/_work/ramen/ramen/test/drenv/kubectl.py", line 129, in wait
          _watch("wait", *args, context=context, log=log)
        File "/home/github/actions-runner/_work/ramen/ramen/test/drenv/kubectl.py", line 145, in _watch
          for line in commands.watch(*cmd, input=input):
        File "/home/github/actions-runner/_work/ramen/ramen/test/drenv/commands.py", line 148, in watch
          raise Error(args, error, exitcode=p.returncode)
      drenv.commands.Error: Command failed:
         command: ('kubectl', 'wait', '--context', 'rdr-hub', 'managedcluster/rdr-dr1', '--for=condition=ManagedClusterConditionAvailable', '--timeout=600s')
         exitcode: 1
         error:
            error: timed out waiting for the condition on managedclusters/rdr-dr1
```

**Comment by nirs** [comment]
Tested using this script:

```sh
#!/bin/sh

runs=${1:-10}
name=${2:-$(date +%Y-%m-%d-%H-%M-%S)}

env="envs/regional-dr.yaml"
log="stress-$name.log"

passed=0
failed=0

start_env() {
        drenv start "$env" 2>>"$log"
}

delete_env() {
        drenv delete "$env" 2>>"$log"
}

echo "running $runs iterations"
echo "logging to $log"

run_started=$(date +%s)

for n in $(seq $runs); do
        echo -n "attempt $n ... "

        started=$(date +%s)
        start_env
        rc=$?
        finished=$(date +%s)

        if [ $rc -eq 0 ]; then
                echo "passed in $((finished - started)) seconds"
                passed=$((passed+1))
        else
                echo "failed in $((finished - started)) seconds"
                failed=$((failed+1))
        fi

        delete_env
done

run_finished=$(date +%s)

echo "$runs runs, $passed passed, $failed failed in $((run_finished - run_started)) seconds"
```

**Comment by nirs** [comment]
# Errors from 4 cpus run

```
drenv.commands.Error: Command failed:
   command: ('addons/rbd-mirror/start', 'dr1', 'dr2')
   exitcode: 1
   error:
      Traceback (most recent call last):
        File "/home/nsoffer/src/ramen/test/addons/rbd-mirror/start", line 166, in <module>
          configure_rbd_mirroring(cluster2, cluster1_info)
        File "/home/nsoffer/src/ramen/test/addons/rbd-mirror/start", line 81, in configure_rbd_mirroring
          kubectl.apply(
        File "/home/nsoffer/src/ramen/test/drenv/kubectl.py", line 59, in apply
          _watch("apply", *args, input=input, context=context, log=log)
--
      drenv.commands.Error: Command failed:
         command: ('kubectl', 'apply', '--context', 'dr2', '--filename=-', '--namespace=rook-ceph')
         exitcode: 1
         error:
            error: error when retrieving current configuration of:
            Resource: "/v1, Resource=secrets", GroupVersionKind: "/v1, Kind=Secret"
            Name: "", Namespace: "rook-ceph"
            from server for: "STDIN": resource name may not be empty

2024-03-18 03:56:06,916 INFO    [rdr] Deleting environment
2024-03-18 03:56:06,917 INFO    [dr1] Deleting cluster
--
drenv.commands.Error: Command failed:
   command: ('addons/ocm-cluster/start', 'dr1', 'hub')
   exitcode: 1
   error:
      Traceback (most recent call last):
        File "/home/nsoffer/src/ramen/test/addons/ocm-cluster/start", line 135, in <module>
          deploy(cluster_name, hub_name)
        File "/home/nsoffer/src/ramen/test/addons/ocm-cluster/start", line 47, in deploy
          wait_for_managed_cluster(cluster, hub)
        File "/home/nsoffer/src/ramen/test/addons/ocm-cluster/start", line 113, in wait_for_managed_cluster
          kubectl.wait(
--
      drenv.commands.Error: Command failed:
         command: ('kubectl', 'wait', '--context', 'hub', 'managedcluster/dr1', '--for=condition=ManagedClusterConditionAvailable', '--timeout=600s')
         exitcode: 1
         error:
            error: timed out waiting for the condition on managedclusters/dr1

2024-03-18 04:19:05,833 INFO    [rdr] Deleting environment
2024-03-18 04:19:05,834 INFO    [dr1] Deleting cluster
2024-03-18 04:19:05,835 INFO    [dr2] Deleting cluster
2024-03-18 04:19:05,836 INFO    [hub] Deleting cluster
2024-03-18 04:19:07,890 INFO    [dr2] Cluster deleted in 2.05 seconds
--
drenv.commands.Error: Command failed:
   command: ('addons/rbd-mirror/start', 'dr1', 'dr2')
   exitcode: 1
   error:
      Traceback (most recent call last):
        File "/home/nsoffer/src/ramen/test/addons/rbd-mirror/start", line 166, in <module>
          configure_rbd_mirroring(cluster2, cluster1_info)
        File "/home/nsoffer/src/ramen/test/addons/rbd-mirror/start", line 81, in configure_rbd_mirroring
          kubectl.apply(
        File "/home/nsoffer/src/ramen/test/drenv/kubectl.py", line 59, in apply
          _watch("apply", *args, input=input, context=context, log=log)
--
      drenv.commands.Error: Command failed:
         command: ('kubectl', 'apply', '--context', 'dr2', '--filename=-', '--namespace=rook-ceph')
         exitcode: 1
         error:
            error: error when retrieving current configuration of:
            Resource: "/v1, Resource=secrets", GroupVersionKind: "/v1, Kind=Secret"
            Name: "", Namespace: "rook-ceph"
            from server for: "STDIN": resource name may not be empty

2024-03-18 04:34:58,323 INFO    [rdr] Deleting environment
2024-03-18 04:34:58,324 INFO    [dr1] Deleting cluster
--
drenv.commands.Error: Command failed:
   command: ('addons/rbd-mirror/start', 'dr1', 'dr2')
   exitcode: 1
   error:
      Traceback (most recent call last):
        File "/home/nsoffer/src/ramen/test/addons/rbd-mirror/start", line 163, in <module>
          configure_rbd_mirroring(cluster1, cluster2_info)
        File "/home/nsoffer/src/ramen/test/addons/rbd-mirror/start", line 81, in configure_rbd_mirroring
          kubectl.apply(
        File "/home/nsoffer/src/ramen/test/drenv/kubectl.py", line 59, in apply
          _watch("apply", *args, input=input, context=context, log=log)
--
      drenv.commands.Error: Command failed:
         command: ('kubectl', 'apply', '--context', 'dr1', '--filename=-', '--namespace=rook-ceph')
         exitcode: 1
         error:
            error: error when retrieving current configuration of:
            Resource: "/v1, Resource=secrets", GroupVersionKind: "/v1, Kind=Secret"
            Name: "", Namespace: "rook-ceph"
            from server for: "STDIN": resource name may not be empty

2024-03-18 04:41:44,443 INFO    [rdr] Deleting environment
2024-03-18 04:41:44,445 INFO    [dr1] Deleting cluster
--
drenv.commands.Error: Command failed:
   command: ('addons/rbd-mirror/start', 'dr1', 'dr2')
   exitcode: 1
   error:
      Traceback (most recent call last):
        File "/home/nsoffer/src/ramen/test/addons/rbd-mirror/start", line 175, in <module>
          check_blocklist(cluster2)
        File "/home/nsoffer/src/ramen/test/addons/rbd-mirror/start", line 37, in check_blocklist
          raise RuntimeError(f"Ceph blocklist on cluster {cluster}: {blocklist}")
      RuntimeError: Ceph blocklist on cluster dr2: [{'addr': '192.168.122.215:0/3719410668', 'until': '2024-03-18T23:45:12.995981+0000'}, {'addr': '192.168.122.215:0/1473535966', 'until': '2024-03-18T23:45:12.995981+0000'}, {'addr': '192.168.122.215:0/1935687117', 'until': '2024-03-18T23:45:12.995981+0000'}, {'addr': '192.168.122.215:0/224793792', 'until': '2024-03-18T23:45:12.995981+0000'}, {'addr': '192.168.122.215:6809/3860533110', 'until': '2024-03-18T23:45:12.995981+0000'}, {'addr': '192.168.122.215:6808/3860533110', 'until': '2024-03-18T23:45:12.995981+0000'}]

--
drenv.commands.Error: Command failed:
   command: ('addons/velero/test', 'dr2')
   exitcode: 1
   error:
      Traceback (most recent call last):
        File "/home/nsoffer/src/ramen/test/addons/velero/test", line 164, in <module>
          test(cluster)
        File "/home/nsoffer/src/ramen/test/addons/velero/test", line 55, in test
          delete_backup(cluster, BACKUP)
        File "/home/nsoffer/src/ramen/test/addons/velero/test", line 119, in delete_backup
          while get_backup(cluster, name):
--
      drenv.commands.Error: Command failed:
         command: ('velero', 'backup', 'get', '--output=json', '--kubecontext=dr2')
         exitcode: 1
         error:
            An error occurred: Get "https://192.168.122.8:8443/api?timeout=32s": net/http: TLS handshake timeout

2024-03-18 06:08:08,304 INFO    [rdr] Deleting environment
2024-03-18 06:08:08,305 INFO    [dr1] Deleting cluster
2024-03-18 06:08:08,306 INFO    [dr2] Deleting cluster
2024-03-18 06:08:08,308 INFO    [hub] Deleting cluster
2024-03-18 06:08:10,466 INFO    [dr1] Cluster deleted in 2.16 seconds
--
drenv.commands.Error: Command failed:
   command: ('addons/ocm-cluster/start', 'dr1', 'hub')
   exitcode: 1
   error:
      Traceback (most recent call last):
        File "/home/nsoffer/src/ramen/test/addons/ocm-cluster/start", line 135, in <module>
          deploy(cluster_name, hub_name)
        File "/home/nsoffer/src/ramen/test/addons/ocm-cluster/start", line 47, in deploy
          wait_for_managed_cluster(cluster, hub)
        File "/home/nsoffer/src/ramen/test/addons/ocm-cluster/start", line 113, in wait_for_managed_cluster
          kubectl.wait(
--
      drenv.commands.Error: Command failed:
         command: ('kubectl', 'wait', '--context', 'hub', 'managedcluster/dr1', '--for=condition=ManagedClusterConditionAvailable', '--timeout=600s')
         exitcode: 1
         error:
            error: timed out waiting for the condition on managedclusters/dr1

2024-03-18 07:04:19,199 INFO    [rdr] Deleting environment
2024-03-18 07:04:19,200 INFO    [dr1] Deleting cluster
2024-03-18 07:04:19,201 INFO    [dr2] Deleting cluster
2024-03-18 07:04:19,202 INFO    [hub] Deleting cluster
2024-03-18 07:04:21,250 INFO    [hub] Cluster deleted in 2.05 seconds
--
drenv.commands.Error: Command failed:
   command: ('addons/rbd-mirror/start', 'dr1', 'dr2')
   exitcode: 1
   error:
      Traceback (most recent call last):
        File "/home/nsoffer/src/ramen/test/addons/rbd-mirror/start", line 163, in <module>
          configure_rbd_mirroring(cluster1, cluster2_info)
        File "/home/nsoffer/src/ramen/test/addons/rbd-mirror/start", line 81, in configure_rbd_mirroring
          kubectl.apply(
        File "/home/nsoffer/src/ramen/test/drenv/kubectl.py", line 59, in apply
          _watch("apply", *args, input=input, context=context, log=log)
--
      drenv.commands.Error: Command failed:
         command: ('kubectl', 'apply', '--context', 'dr1', '--filename=-', '--namespace=rook-ceph')
         exitcode: 1
         error:
            error: error when retrieving current configuration of:
            Resource: "/v1, Resource=secrets", GroupVersionKind: "/v1, Kind=Secret"
            Name: "", Namespace: "rook-ceph"
            from server for: "STDIN": resource name may not be empty

2024-03-18 07:36:36,326 INFO    [rdr] Deleting environment
2024-03-18 07:36:36,328 INFO    [dr1] Deleting cluster
--
drenv.commands.Error: Command failed:
   command: ('addons/rbd-mirror/start', 'dr1', 'dr2')
   exitcode: 1
   error:
      Traceback (most recent call last):
        File "/home/nsoffer/src/ramen/test/addons/rbd-mirror/start", line 174, in <module>
          check_blocklist(cluster1)
        File "/home/nsoffer/src/ramen/test/addons/rbd-mirror/start", line 37, in check_blocklist
          raise RuntimeError(f"Ceph blocklist on cluster {cluster}: {blocklist}")
      RuntimeError: Ceph blocklist on cluster dr1: [{'addr': '192.168.122.48:0/575213926', 'until': '2024-03-19T04:02:23.072598+0000'}, {'addr': '192.168.122.48:6808/1973792600', 'until': '2024-03-19T04:02:23.072598+0000'}, {'addr': '192.168.122.48:0/3850428145', 'until': '2024-03-19T04:02:23.072598+0000'}, {'addr': '192.168.122.48:0/99458170', 'until': '2024-03-19T04:02:23.072598+0000'}, {'addr': '192.168.122.48:6809/1973792600', 'until': '2024-03-19T04:02:23.072598+0000'}, {'addr': '192.168.122.48:0/1639922505', 'until': '2024-03-19T04:02:23.072598+0000'}]

--
drenv.commands.Error: Command failed:
   command: ('addons/rbd-mirror/start', 'dr1', 'dr2')
   exitcode: 1
   error:
      Traceback (most recent call last):
        File "/home/nsoffer/src/ramen/test/addons/rbd-mirror/start", line 174, in <module>
          check_blocklist(cluster1)
        File "/home/nsoffer/src/ramen/test/addons/rbd-mirror/start", line 37, in check_blocklist
          raise RuntimeError(f"Ceph blocklist on cluster {cluster}: {blocklist}")
      RuntimeError: Ceph blocklist on cluster dr1: [{'addr': '192.168.122.209:0/1845700569', 'until': '2024-03-19T04:29:24.401900+0000'}, {'addr': '192.168.122.209:0/3286118577', 'until': '2024-03-19T04:29:24.401900+0000'}, {'addr': '192.168.122.209:0/3442007034', 'until': '2024-03-19T04:29:24.401900+0000'}, {'addr': '192.168.122.209:6809/3612715280', 'until': '2024-03-19T04:29:24.401900+0000'}, {'addr': '192.168.122.209:0/2707588350', 'until': '2024-03-19T04:29:24.401900+0000'}, {'addr': '192.168.122.209:6808/3612715280', 'until': '2024-03-19T04:29:24.401900+0000'}]

--
drenv.commands.Error: Command failed:
   command: ('addons/rbd-mirror/start', 'dr1', 'dr2')
   exitcode: 1
   error:
      Traceback (most recent call last):
        File "/home/nsoffer/src/ramen/test/addons/rbd-mirror/start", line 174, in <module>
          check_blocklist(cluster1)
        File "/home/nsoffer/src/ramen/test/addons/rbd-mirror/start", line 37, in check_blocklist
          raise RuntimeError(f"Ceph blocklist on cluster {cluster}: {blocklist}")
      RuntimeError: Ceph blocklist on cluster dr1: [{'addr': '192.168.122.134:0/3047068919', 'until': '2024-03-19T05:16:16.582861+0000'}, {'addr': '192.168.122.134:6809/1874544862', 'until': '2024-03-19T05:16:16.582861+0000'}, {'addr': '192.168.122.134:6808/1874544862', 'until': '2024-03-19T05:16:16.582861+0000'}, {'addr': '192.168.122.134:0/938679790', 'until': '2024-03-19T05:16:16.582861+0000'}, {'addr': '192.168.122.134:0/529438490', 'until': '2024-03-19T05:16:16.582861+0000'}, {'addr': '192.168.122.134:0/4114029324', 'until': '2024-03-19T05:16:16.582861+0000'}]
```

**Comment by rakeshgm** [comment]
i used these cpu counts when i deploy prometheus, but isn't this too much to run on our laptops in terms of cpu usage?? does it slow down the host machine?

**Comment by nirs** [comment]
> i used these cpu counts when i deploy prometheus, but isn't this too much to run on our laptops in terms of cpu usage?? does it slow down the host machine?

This is a good point. I tested locally on Lennovo P1 Gen 3 (i7-10850H) with 6 cores and 12 threads. It works fine with 4 cpus, but does not seems to make much difference.

I think we need to have setting that works for most case. If you try to run in special conditions (e.g. weak laptop) you may need to tweak the environment. You can keep your
own env file and use it for testing without modifying the source. For example:

    cp envs/regional-dr.yaml ~/envs/regional-dr.yaml
    edit ~/envs/regional-dr.yaml
    drenv start ~/envs/regional-dr.yaml

In the future I think we need to support kustomization for env files to make this easier.

**Review by rakeshgm — APPROVED** [review]

**Comment by ShyamsundarR** [comment]
If we are changing the timeouts shouldn't we make it configurable? I though that was what we wanted to aim for when we moved to 600s for setups that we had to retry multiple time due to lower timeouts.

While these timeouts are causing failures to be reported late, on slower machines it helps.

**Comment by nirs** [comment]
We can make the configurable, but it requires much more work. I can do this in the next sprint.

Basically it means converting all kubectl functions to proper python functions, so timeout is an argument to the call. Then we can tweak the timeouts (e.g multiple by factor) based on local configuration (e.g. ~/.config/drenv/config.yaml).

**Comment by nirs** [comment]
Results from last run:

Tested 2 vms:
- e2e-rdr: kvm, 10 cpus, 24g RAM, running on rhocs-bm5, fedora 39, 6.7.10-200.fc39.x86_64
- drvm: vmware, 8 cpus, 64g RAM, running in blr lab, fedora 39, 6.7.11-200.fc39.x86_64

## Stats

| vm       | passed | failed | rate(%) | time/run(s) |
|----------|--------|--------|--------|--------------|
| e2e-rdr  |     99 |      1 |   99.0 |          610 |
| drvm     |     96 |      4 |   96.0 |          816 |

## Errors

| count | addon | hook | error |
|-------|-------|------|-------|
| 4     | rbd-mirror   | start | timeout waiting for daemon_health |
| 1     | minio        | start | timeout waiting for deployment |

The minio error looks like a real issue with the deployment. At the same time minio on other clsuter was deployed normally in less than 20 seocnds:

```
2024-04-04 23:27:46,375 INFO    [dr2/2] Running addons/minio/start
2024-04-04 23:27:46,490 DEBUG   [dr2/2] Deploying minio
2024-04-04 23:27:46,752 DEBUG   [dr2/2] namespace/minio created
2024-04-04 23:27:46,773 DEBUG   [dr2/2] persistentvolumeclaim/minio-storage-pvc created
2024-04-04 23:27:46,787 DEBUG   [dr2/2] deployment.apps/minio created
2024-04-04 23:27:46,822 DEBUG   [dr2/2] service/minio created
2024-04-04 23:27:46,825 DEBUG   [dr2/2] Waiting until minio is rolled out
2024-04-04 23:27:47,019 DEBUG   [dr2/2] Waiting for deployment "minio" rollout to finish: 0 of 1 updated replicas are available...
...
2024-04-04 23:33:04,187 ERROR   Command failed
Traceback (most recent call last):
  ...
drenv.commands.Error: Command failed:
   command: ('addons/minio/start', 'dr1')
   exitcode: 1
   error:
      Traceback (most recent call last):
        ...
      drenv.commands.Error: Command failed:
         command: ('kubectl', 'rollout', '--context', 'dr1', 'status', 'deployment/minio', '--namespace=minio', '--timeout=300s')
         exitcode: 1
         error:
            error: timed out waiting for the condition
```

```
2024-04-04 23:28:03,584 INFO    [dr1/2] Running addons/minio/start
2024-04-04 23:28:03,718 DEBUG   [dr1/2] Deploying minio
2024-04-04 23:28:03,975 DEBUG   [dr1/2] namespace/minio created
2024-04-04 23:28:03,990 DEBUG   [dr1/2] persistentvolumeclaim/minio-storage-pvc created
2024-04-04 23:28:04,006 DEBUG   [dr1/2] deployment.apps/minio created
2024-04-04 23:28:04,066 DEBUG   [dr1/2] service/minio created
2024-04-04 23:28:04,069 DEBUG   [dr1/2] Waiting until minio is rolled out
2024-04-04 23:28:04,154 DEBUG   [dr1/2] Waiting for deployment "minio" rollout to finish: 0 of 1 updated replicas are available...
2024-04-04 23:28:05,112 DEBUG   [dr2/2] deployment "minio" successfully rolled out
2024-04-04 23:28:05,115 DEBUG   [dr2/2] Waiting until minio service is available (attempt 1/5)
2024-04-04 23:28:05,260 DEBUG   [dr2/2] minio is ready in 0.01 seconds
2024-04-04 23:28:05,261 DEBUG   [dr2/2] Setting mc alias dr2 (attempt 1/5)
2024-04-04 23:28:05,547 DEBUG   [dr2/2] Set mc alias in 0.43 seconds
2024-04-04 23:28:05,547 DEBUG   [dr2/2] Creating bucket 'dr2/bucket'
2024-04-04 23:28:05,651 INFO    [dr2/2] addons/minio/start completed in 19.28 seconds
```

The rbd-mirror looks like a real issue in ceph (#1322). Trying to reproduce and get a broken environment for collecting more data.

**Review by ShyamsundarR — APPROVED** [review]

**Pull request merged**
